version: '3.8'

services:
  bge-m3-training:
    build: .
    container_name: bge-m3-flagembedding
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - WANDB_MODE=disabled
      - HF_HUB_CACHE=/workspace/.cache/huggingface/hub
    volumes:
      # Mount your data directory
      - ./data:/workspace/data:ro
      # Mount output directory to persist results
      - ./outputs:/workspace/outputs
      # Mount cache directory for HuggingFace models
      - ./cache:/workspace/.cache
      # Mount your custom training data (optional)
      - ./custom_data:/workspace/custom_data:ro
    working_dir: /workspace
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu] 